asr:
  MFCC: 
    frame_len : 0.04
    hop_len : 0.01
    FFT_size : 1024
    window : "hann"
    n_mfcc : 30
    dct_type : 2
    dct_norm : "ortho"

preprocessing:
  resampling :  
    filterOrder : 120
    window : "hamming"
    targetFrequency : 16000
  VAD: 
    f_min : 50
    f_max : 8000
    frame_len : 0.1
    threshold : 0.2

tts:
  tools:
    frameLen : 0.02 # in seconds
    frameOverlap : 0.5 # [0;1)
    Threshold : 0.35