asr:
  MFCC: 
    frame_len : 0.04
    hop_len : 0.01
    FFT_size : 1024
    window : "hann"
    n_mfcc : 30
    dct_type : 2
    dct_norm : "ortho"
  GMM:
    if_train : True
    n_components : 8 
    covariance_type : "full" 
    tol : 0.001 
    reg_covar : 0.000001
    max_iter : 100 
    n_init : 10 
    init_params : "kmeans" 
    random_state : 10
    warm_start : False 
    verbose : 0 
    verbose_interval : 10

preprocessing:
  resampling :  
    filterOrder : 120
    window : "hamming"
    targetFrequency : 16000
  VAD: 
    f_min : 50
    f_max : 8000
    frame_len : 0.1
    threshold : 0.2

tts:
  tools:
    frameLen : 0.022 # in seconds
    frameOverlap : 0.3 # [0;1)
    Threshold : 0.35